# Generated by Django 4.2.6 on 2023-11-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_brand', models.CharField(blank=True, max_length=255, verbose_name='Марка авто')),
            ],
        ),
        migrations.CreateModel(
            name='Crm_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chek', models.BooleanField(default=False, verbose_name='Выбор')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('telephone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('vin', models.CharField(blank=True, max_length=255, verbose_name='VIN-номер')),
                ('ord', models.CharField(blank=True, max_length=255, verbose_name='Заказы')),
                ('bonuses', models.CharField(blank=True, max_length=255, verbose_name='Бонусы')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_client.brandauto')),
            ],
        ),
    ]
