# Generated by Django 4.2.6 on 2023-10-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crm_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('car', models.CharField(max_length=255, verbose_name='Автомобиль')),
                ('telephone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('vin', models.CharField(max_length=255, verbose_name='VIN-номер')),
                ('ord', models.CharField(max_length=255, verbose_name='Заказы')),
                ('bonuses', models.CharField(max_length=255, verbose_name='Бонусы')),
                ('data_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
    ]
