# Generated by Django 4.2.6 on 2023-10-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_brand', models.CharField(blank=True, max_length=255, verbose_name='Марка авто')),
            ],
        ),
        migrations.AlterField(
            model_name='crm_client',
            name='bonuses',
            field=models.CharField(blank=True, max_length=255, verbose_name='Бонусы'),
        ),
        migrations.AlterField(
            model_name='crm_client',
            name='car',
            field=models.CharField(blank=True, max_length=255, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='crm_client',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='crm_client',
            name='ord',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заказы'),
        ),
        migrations.AlterField(
            model_name='crm_client',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='crm_client',
            name='surname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='crm_client',
            name='vin',
            field=models.CharField(blank=True, max_length=255, verbose_name='VIN-номер'),
        ),
    ]
