# Generated by Django 4.2.6 on 2023-11-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_client', '0002_brandauto_alter_crm_client_bonuses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_client',
            name='chek',
            field=models.BooleanField(default=False, verbose_name='Выбор'),
        ),
    ]
