# Generated by Django 4.1.13 on 2024-03-12 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_client', '0003_alter_crm_client_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_brand', models.CharField(blank=True, max_length=255, verbose_name='Модель авто')),
            ],
        ),
        migrations.AlterField(
            model_name='crm_client',
            name='car',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='crm_client.brandauto'),
        ),
        migrations.AlterField(
            model_name='crm_client',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='crm_client',
            name='model_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm_client.modelauto'),
        ),
    ]
