# Generated by Django 4.1.13 on 2024-03-12 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_client', '0004_modelauto_alter_crm_client_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelauto',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm_client.brandauto'),
        ),
    ]
