# Generated by Django 4.1.13 on 2024-11-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_client', '0005_modelauto_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelauto',
            old_name='brand',
            new_name='auto_brand',
        ),
    ]
