# Generated by Django 5.1.3 on 2024-12-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_client', '0006_rename_brand_modelauto_auto_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandauto',
            name='sort',
            field=models.IntegerField(null=True, verbose_name='Позиция'),
        ),
    ]
